# Uses http://pre-commit.com
#
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master  # or specific git tag
    hooks:
      - id: git-check
      - id: require-ascii
      - id: shellcheck
      - id: shfmt
