#!/usr/bin/env osascript
try
  set PID to (do shell script "pgrep -f 'java.*minecraft'") as integer
  tell application "System Events"
    set frontmost of every process whose unix id is PID to true
  end tell
on error errmsg number errnr
  tell application "Minecraft" to activate
end try
